######################################################################
#
# File name : NIU_simulate.do
# Created on: Wed Jan 03 10:04:44 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -L xpm -L fifo_generator_v13_1_1 -L ten_gig_eth_pcs_pma_v6_0_5 -L ten_gig_eth_mac_v15_1_1 -L axis_infrastructure_v1_1_0 -L axis_data_fifo_v1_1_10 -L axis_register_slice_v1_1_9 -lib xil_defaultlib xil_defaultlib.tc_niu xil_defaultlib.glbl

do {NIU_wave.do}

view wave
view structure
view signals

do {NIU.udo}

run 1000ns
